---
title: "Top 10 US Cities by Polulation"
author: "Kenney Snell"
date: "December 28, 2017"
output:
  html_document: default
  ---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
```

## December 28, 2017

```{r Top_pol,comment= FALSE}
library(leaflet)
md_cities <- data.frame(name = c("New York", " Los Angeles", " Chicago", 
                                 "Houston", "Phoenix","Philadelphia", 
                                 "San Antonio", "San Diego", "Dallas",
                                 "San Jose"),
    pop = c(8537673, 3976322, 2704958, 2303482, 1615017,
           1567872, 1492510, 1406630, 1317929, 1025350),
    
   lat = c(40.6635,34.0194,41.8376,29.7866,33.5722,
           40.0094,29.4724,32.8153,32.7933,37.2967), 
   lng = c(-73.9387,-118.4108,-87.6818,-95.3909,-112.0901,
           -75.1333,-98.5251,-117.135,-96.7665,-121.8189),
   col = c("red", "blue", "green", "pink", "yellow", "black", "purple","orange", "aqua","brown"),
    stringsAsFactors = FALSE)
                

   
md_cities %>%
  leaflet() %>%
  addTiles() %>%
 
  addCircles(weight = 1, radius = sqrt(md_cities$pop) * 40) %>%
addCircleMarkers(color = md_cities$col) %>%
  addLegend(labels = 1:10, colors = c("red", "blue", "green", "pink", "yellow", "black", "purple","orange", "aqua","brown"))

```





```

